import React,{useEffect,useState} from 'react';
import { Plus, Printer, Settings, Search, X, FileText, Download } from 'lucide-react';
import { useSettings } from '../context/SettingsContext';
import { InvoicePaper } from './InvoiceDocument';
import { invoiceTotals } from '../../invoice-math';
import ImageUploadButton from './ImageUploadButton';

export default function InvoicesTab() {
  const {bookings}=useSettings();
  const [invoices,setInvoices]=useState<any[]>([]),[issuer,setIssuer]=useState<any>(null);
  const [showSettings,setShowSettings]=useState(false),[creating,setCreating]=useState(false),[preview,setPreview]=useState(false);
  const [search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [bookingId,setBookingId]=useState(''),[date,setDate]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));
  const [buyer,setBuyer]=useState({name:'',address:'',taxId:'',branch:'สำนักงานใหญ่',phone:''});
  const [items,setItems]=useState([{description:'',quantity:1,unitPrice:0}]);
  const [payment,setPayment]=useState({method:'cash',bank:'',branch:'',chequeNo:'',date:''});
  const [receiver,setReceiver]=useState('');
  async function api(url:string,method='GET',body?:any){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
  async function load(){try{const [list,config]=await Promise.all([api('/api/invoices'),api('/api/invoices/settings')]);setInvoices(list.invoices);setIssuer(config.settings);}catch(e:any){setError(e.message);}}
  useEffect(()=>{void load();},[]);
  const booking=bookings.find(b=>b.id===bookingId);
  const eligible=bookings.filter(b=>['Paid','Checked-In','Completed'].includes(b.status) && !invoices.some(i=>i.bookingId===b.id&&i.status!=='void'));
  function choose(id:string){setBookingId(id);const b=bookings.find(b=>b.id===id);if(b){setBuyer({name:b.guestName,address:'',taxId:'',branch:'สำนักงานใหญ่',phone:b.guestPhone});setItems([{description:b.roomName||b.roomType,quantity:1,unitPrice:b.totalPrice}]);}}
  async function issue(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await api('/api/invoices','POST',{bookingId,date,buyer,items,payment,receiver});setCreating(false);setPreview(false);await load();window.location.assign('/invoice/'+d.invoice.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const totals=invoiceTotals(items,Number(issuer?.vatRate||0));
  const field='w-full rounded-lg border border-neutral-300 bg-white text-neutral-900 px-3 py-2 text-sm focus:outline-orange-500';
  const button='inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold border border-neutral-300 bg-white text-neutral-800 hover:bg-neutral-100';
  const labels:any={companyNameEn:'ชื่อบริษัท (อังกฤษ)',companyNameTh:'ชื่อบริษัท (ไทย)',branch:'สาขา',address:'ที่อยู่บริษัท',phone:'โทรศัพท์',email:'อีเมล',taxId:'เลขประจำตัวผู้เสียภาษี',vatRate:'VAT (%) — ราคารวมภาษี',prefix:'คำนำหน้าเลขเอกสาร',footer:'ข้อความท้ายเอกสาร'};
  return <section className="space-y-6 text-neutral-900">
    <div className="flex flex-wrap justify-between items-start gap-4"><div><h2 className="text-2xl font-bold">ใบเสร็จรับเงิน / ใบกำกับภาษี</h2><p className="text-sm text-neutral-500 mt-1">ออกเอกสารจากยอดรับชำระ · แบบฟอร์ม A4 · พิมพ์ซ้ำได้</p></div><div className="flex flex-wrap gap-2"><a className={button} href="/api/backup"><Download size={16}/>สำรองข้อมูล</a><button className={button} onClick={()=>setShowSettings(!showSettings)}><Settings size={16}/>ข้อมูลผู้ออกเอกสาร</button><button className={button+' !bg-orange-700 !text-white !border-orange-700'} onClick={()=>{setCreating(true);setError('');if(eligible[0])choose(eligible[0].id);}}><Plus size={16}/>ออกใบกำกับภาษี</button></div></div>
    {error&&<p role="alert" className="rounded-lg bg-red-50 text-red-700 p-4">{error}</p>}
    {showSettings&&issuer&&<form className="bg-white rounded-xl border p-6 space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/api/invoices/settings','PUT',{settings:issuer});setShowSettings(false);setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
      <h3 className="font-bold">ข้อมูลบริษัทตามแบบฟอร์ม</h3><p className="text-sm text-neutral-500">การแก้ไขมีผลกับเอกสารใหม่ เอกสารที่ออกแล้วจะเก็บข้อมูลเดิม</p><div className="grid md:grid-cols-2 gap-4">{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm space-y-1 block"><span>{label as string}</span><input className={field} type={key==='vatRate'?'number':'text'} value={issuer[key]??''} onChange={e=>setIssuer({...issuer,[key]:e.target.value})} required={['companyNameTh','address','taxId','prefix'].includes(key)}/></label>)}</div>
      <div className="flex items-center gap-4"><label className="flex-1 text-sm">URL โลโก้<input className={field} value={issuer.logoUrl||''} onChange={e=>setIssuer({...issuer,logoUrl:e.target.value})}/></label><ImageUploadButton onUploadSuccess={url=>setIssuer({...issuer,logoUrl:url})}/></div>
      <button disabled={busy} className={button}>บันทึกข้อมูลบริษัท</button>
    </form>}
    <div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b flex gap-2 items-center"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาเลขเอกสาร ชื่อลูกค้า หรือเลขการจอง" className="w-full outline-none text-sm"/></div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-neutral-50 text-neutral-500"><tr>{['เลขที่เอกสาร','วันที่','ลูกค้า','ยอดรวม','สถานะ','จัดการ'].map(s=><th className="px-4 py-3" key={s}>{s}</th>)}</tr></thead><tbody>{invoices.filter(i=>(i.number+i.buyer.name+i.bookingId).toLowerCase().includes(search.toLowerCase())).map(i=><tr key={i.id} className="border-t"><td className="px-4 py-4 font-mono">{i.number}<small className="block text-neutral-400">{i.bookingId}</small></td><td className="px-4">{i.date}</td><td className="px-4">{i.buyer.name}</td><td className="px-4">{i.total.toLocaleString('th-TH',{minimumFractionDigits:2})}</td><td className="px-4">{i.status==='void'?'ยกเลิก':'ออกแล้ว'}</td><td className="px-4"><a className="text-orange-700 inline-flex gap-1" href={'/invoice/'+i.id} target="_blank" rel="noreferrer"><Printer size={16}/>พิมพ์</a>{i.status!=='void'&&<button className="ml-3 text-red-600" onClick={async()=>{const reason=window.prompt('เหตุผลการยกเลิกเอกสาร (เก็บประวัติไว้และไม่ใช้เลขซ้ำ)');if(!reason)return;try{await api('/api/invoices/'+i.id+'/void','POST',{reason});await load();}catch(e:any){setError(e.message);}}}>ยกเลิก</button>}</td></tr>)}</tbody></table></div>{!invoices.length&&<div className="py-16 text-center text-neutral-400"><FileText className="mx-auto mb-3" size={32}/><p>ยังไม่มีเอกสาร</p><p className="text-xs mt-2">ตรวจสอบการชำระเงินในรายการจอง แล้วเปลี่ยนสถานะเป็น Paid เพื่อเริ่มออกเอกสาร</p></div>}</div>
    {creating&&<div className="fixed inset-0 z-[100] bg-black/60 overflow-y-auto p-4"><form onSubmit={issue} className="max-w-3xl mx-auto bg-white rounded-xl p-6 space-y-5 my-6"><div className="flex justify-between"><h3 className="text-xl font-bold">ออกใบเสร็จ / ใบกำกับภาษี</h3><button type="button" aria-label="ปิด" onClick={()=>setCreating(false)}><X/></button></div><p className="text-sm text-neutral-500">ตรวจสอบข้อมูลให้ครบก่อนออกเอกสาร เลขที่เอกสารจะถูกกำหนดเมื่อบันทึก</p>
      {error&&<p role="alert" className="text-red-700 bg-red-50 p-3">{error}</p>}
      <div className="grid md:grid-cols-2 gap-4"><label className="text-sm">รายการจองที่รับชำระแล้ว<select required className={field} value={bookingId} onChange={e=>choose(e.target.value)}><option value="">เลือกรายการจอง</option>{eligible.map(b=><option key={b.id} value={b.id}>{b.id} · {b.guestName}</option>)}</select></label><label className="text-sm">วันที่เอกสาร<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label></div>
      {!eligible.length&&<p className="text-amber-700">ไม่มีรายการจองที่พร้อมออกเอกสาร กรุณาตรวจสอบการรับชำระเงินก่อน</p>}
      <div className="grid md:grid-cols-2 gap-4">{Object.entries({name:'ชื่อลูกค้า / บริษัท',taxId:'เลขผู้เสียภาษี (13 หลัก)',address:'ที่อยู่',branch:'สาขา',phone:'โทรศัพท์'}).map(([key,label])=><label key={key} className={'text-sm '+(key==='address'?'md:col-span-2':'')}>{label}{key==='address'?<textarea required className={field} rows={2} value={buyer.address} onChange={e=>setBuyer({...buyer,address:e.target.value})}/>:<input required={['name','taxId'].includes(key)} className={field} value={(buyer as any)[key]} pattern={key==='taxId'?'[0-9]{13}':undefined} onChange={e=>setBuyer({...buyer,[key]:e.target.value})}/>}</label>)}</div>
      <div className="space-y-3"><h4 className="font-bold">รายการ (ราคาต่อหน่วยรวม VAT)</h4>{items.map((item,index)=><div key={index} className="grid grid-cols-12 gap-2"><input aria-label={'รายการ '+(index+1)} required className={field+' col-span-6'} maxLength={240} value={item.description} onChange={e=>setItems(items.map((v,j)=>j===index?{...v,description:e.target.value}:v))}/><input aria-label={'จำนวน '+(index+1)} required type="number" min="1" step="1" className={field+' col-span-2'} value={item.quantity} onChange={e=>setItems(items.map((v,j)=>j===index?{...v,quantity:Number(e.target.value)}:v))}/><input aria-label={'ราคา '+(index+1)} required type="number" min="0" step="0.01" className={field+' col-span-3'} value={item.unitPrice} onChange={e=>setItems(items.map((v,j)=>j===index?{...v,unitPrice:Number(e.target.value)}:v))}/><button type="button" aria-label="ลบรายการ" disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==index))}><X size={16}/></button></div>)}<button type="button" className="text-sm text-orange-700" disabled={items.length>=8} onClick={()=>setItems([...items,{description:'',quantity:1,unitPrice:0}])}>+ เพิ่มรายการ</button><p className="text-right font-bold">รวม {totals.total.toLocaleString('th-TH',{minimumFractionDigits:2})} บาท · VAT {totals.vat.toFixed(2)} บาท</p><p className="text-right text-xs text-neutral-500">ยอดรับชำระตามการจอง: {booking?.totalPrice.toLocaleString()} บาท</p></div>
      <div className="grid md:grid-cols-2 gap-4"><label className="text-sm">วิธีรับชำระ<select className={field} value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="cash">เงินสด</option><option value="transfer">เงินโอน</option><option value="cheque">เช็ค</option><option value="card">บัตร</option></select></label><label className="text-sm">ชื่อผู้รับเงิน<input className={field} value={receiver} onChange={e=>setReceiver(e.target.value)}/></label>{payment.method!=='cash'&&Object.entries({bank:'ธนาคาร',branch:'สาขา',chequeNo:'เลขอ้างอิง / เช็ค',date:'วันที่รับชำระ'}).map(([key,label])=><label key={key} className="text-sm">{label}<input type={key==='date'?'date':'text'} className={field} value={(payment as any)[key]} onChange={e=>setPayment({...payment,[key]:e.target.value})}/></label>)}</div>
      <div className="flex justify-end gap-3"><button type="button" className={button} onClick={()=>setPreview(true)}>ดูตัวอย่าง A4</button><button disabled={busy||!bookingId} className={button+' !bg-orange-700 !text-white'}>{busy?'กำลังบันทึก…':'ออกเอกสารและเปิดพิมพ์'}</button></div>
    </form></div>}
    {preview&&issuer&&<div className="fixed inset-0 z-[110] overflow-auto bg-neutral-500/95 p-5"><div className="flex justify-center mb-4"><button className={button} onClick={()=>setPreview(false)}>ปิดตัวอย่าง กลับไปแก้ไข</button></div><InvoicePaper draft invoice={{issuer,buyer,items,payment,receiver,date,number:'(รันเลขเมื่อออกเอกสาร)',checkIn:booking?.checkIn,checkOut:booking?.checkOut,...totals}}/></div>}
  </section>;
}

