import React,{useEffect,useState} from 'react';
import { Bell, Mail, MessageCircle, RefreshCw, Save, CheckCircle } from 'lucide-react';
import {useSettings} from '../context/SettingsContext';
import ImageUploadButton from './ImageUploadButton';

export default function NotificationsTab(){
  const {refreshSettings}=useSettings();
  const [config,setConfig]=useState<any>(null),[smtp,setSmtp]=useState<any>({}),[bank,setBank]=useState<any>({}),[recipients,setRecipients]=useState<any[]>([]);
  const [jobs,setJobs]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function api(url:string,method='GET',body?:any){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
  async function load(){try{const [c,j,p]=await Promise.all([api('/api/notifications/settings'),api('/api/notifications/logs'),api('/api/payments')]);setConfig(c.settings);setSmtp(c.smtp);setBank(c.paymentSettings);setRecipients(c.recipients);setJobs(j.jobs);setPayments(p.payments);}catch(e:any){setError(e.message);}}
  useEffect(()=>{void load();},[]);
  async function action(fn:()=>Promise<any>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const field='w-full rounded-lg border border-neutral-300 bg-white text-neutral-900 px-3 py-2 text-sm';
  const button='rounded-lg border border-neutral-300 px-4 py-2 text-sm bg-white text-neutral-800 inline-flex items-center gap-2 disabled:opacity-50';
  const labels:any={sent:'ส่งสำเร็จ',pending:'รอส่ง / รอลองใหม่',failed:'ส่งไม่สำเร็จ',sending:'กำลังส่ง'};
  if(!config)return <p>{error||'กำลังโหลดการตั้งค่า…'}</p>;
  return <section className="space-y-6 text-neutral-900"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold flex gap-2 items-center"><Bell/>แจ้งเตือนและตรวจสอบการโอน</h2><p className="text-neutral-500 text-sm mt-2">แจ้งการจองใหม่และการแจ้งโอนผ่านอีเมล / LINE</p></div><button className={button} onClick={()=>void load()}><RefreshCw size={16}/>รีเฟรชสถานะ</button></div>
    {error&&<p role="alert" className="p-4 bg-red-50 text-red-700 rounded-lg">{error}</p>}{message&&<p role="status" className="p-4 bg-green-50 text-green-800 rounded-lg">{message}</p>}
    <form className="space-y-5" onSubmit={e=>{e.preventDefault();void action(async()=>{await api('/api/notifications/settings','PUT',{settings:config,smtp,paymentSettings:bank});setMessage('บันทึกการตั้งค่าแล้ว');await load();});}}>
      <div className="bg-white border rounded-xl p-5 space-y-4"><h3 className="font-bold">เหตุการณ์ที่ต้องการแจ้งเตือน</h3><div className="flex flex-wrap gap-6">{Object.entries({bookingEnabled:'มีการจองใหม่',paymentEnabled:'ลูกค้าแจ้งโอนเงิน',customerEmail:'ส่งอีเมลรับเรื่องให้ลูกค้าด้วย'}).map(([key,label])=><label key={key} className="text-sm flex items-center gap-2"><input type="checkbox" checked={config[key]} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>{label}</label>)}</div><label className="block text-sm">URL เว็บไซต์จริง (ใช้ในข้อความแจ้งเตือน)<input type="url" className={field} placeholder="https://your-hotel.com" value={config.siteUrl} onChange={e=>setConfig({...config,siteUrl:e.target.value})}/></label></div>
      <div className="grid xl:grid-cols-2 gap-5"><div className="bg-white border rounded-xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-bold flex gap-2"><Mail size={20}/>อีเมล (SMTP)</h3><label className="text-sm"><input type="checkbox" checked={config.emailEnabled} onChange={e=>setConfig({...config,emailEnabled:e.target.checked})}/> เปิดใช้งาน</label></div><div className="grid md:grid-cols-2 gap-3">{Object.entries({host:'SMTP Host',port:'Port',user:'ชื่อผู้ใช้ SMTP',pass:'รหัสผ่าน / App Password',fromName:'ชื่อผู้ส่ง',fromEmail:'อีเมลผู้ส่ง'}).map(([key,label])=><label key={key} className="text-sm">{label}<input className={field} type={key==='pass'?'password':key==='port'?'number':'text'} value={smtp[key]||''} placeholder={key==='pass'&&smtp.hasPassword?'ตั้งค่าแล้ว — เว้นว่างเพื่อใช้เดิม':''} onChange={e=>setSmtp({...smtp,[key]:e.target.value})}/></label>)}</div><label className="text-sm flex gap-2"><input type="checkbox" checked={smtp.secure||false} onChange={e=>setSmtp({...smtp,secure:e.target.checked})}/>ใช้ SSL/TLS ตั้งแต่เชื่อมต่อ (Port 465)</label><label className="block text-sm">อีเมลผู้รับแจ้งเตือน (คั่นหลายคนด้วย ,)<textarea className={field} value={config.emailRecipients} onChange={e=>setConfig({...config,emailRecipients:e.target.value})}/></label><button type="button" disabled={busy} className={button} onClick={()=>void action(async()=>{const d=await api('/api/notifications/test','POST',{channel:'email'});setMessage(d.job.status==='sent'?'ส่งอีเมลทดสอบสำเร็จ':d.job.error||'เข้าคิวส่งแล้ว');await load();})}>ส่งอีเมลทดสอบจากค่าที่บันทึก</button></div>
      <div className="bg-white border rounded-xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-bold flex gap-2"><MessageCircle size={20}/>LINE Messaging API</h3><label className="text-sm"><input type="checkbox" checked={config.lineEnabled} onChange={e=>setConfig({...config,lineEnabled:e.target.checked})}/> เปิดใช้งาน</label></div><p className="text-xs text-neutral-500">ใช้ LINE Official Account และ Messaging API ของบัญชีโรงแรม</p>{Object.entries({lineToken:'Channel access token',lineSecret:'Channel secret (สำหรับ Webhook)',lineRecipient:'ผู้รับ: userId / groupId / roomId'}).map(([key,label])=><label key={key} className="text-sm block">{label}<input type={key==='lineRecipient'?'text':'password'} className={field} value={config[key]} placeholder={key==='lineToken'&&config.hasLineToken?'ตั้งค่าแล้ว — เว้นว่างเพื่อใช้เดิม':key==='lineSecret'&&config.hasLineSecret?'ตั้งค่าแล้ว — เว้นว่างเพื่อใช้เดิม':''} onChange={e=>setConfig({...config,[key]:e.target.value})}/></label>)}<p className="text-xs break-all">Webhook URL: {config.siteUrl||'https://your-hotel.com'}/api/line/webhook</p><p className="text-xs text-neutral-500">เพิ่ม OA เป็นเพื่อน หรือเชิญ OA เข้ากลุ่ม แล้วส่งข้อความเข้ามา เปิด Use webhook และกรอก Channel secret เพื่อให้ระบบแสดง ID ผู้รับด้านล่าง</p>{recipients.length>0&&<select className={field} value="" onChange={e=>setConfig({...config,lineRecipient:e.target.value})}><option value="">เลือกผู้รับที่พบจาก Webhook</option>{recipients.map(r=><option key={r.id} value={r.id}>{r.type} · {r.id}</option>)}</select>}<a href="https://developers.line.biz/en/docs/messaging-api/sending-messages/" target="_blank" rel="noreferrer" className="text-xs text-orange-700 underline block">คู่มือ LINE Messaging API</a><button type="button" disabled={busy} className={button} onClick={()=>void action(async()=>{const d=await api('/api/notifications/test','POST',{channel:'line'});setMessage(d.job.status==='sent'?'LINE รับข้อความทดสอบแล้ว':d.job.error||'เข้าคิวส่งแล้ว');await load();})}>ส่ง LINE ทดสอบจากค่าที่บันทึก</button></div></div>
      <div className="bg-white border rounded-xl p-5 space-y-4"><h3 className="font-bold">ช่องทางรับชำระที่แสดงให้ลูกค้า</h3><div className="grid md:grid-cols-3 gap-3">{Object.entries({bankName:'ธนาคาร',accountName:'ชื่อบัญชี',accountNumber:'เลขบัญชี'}).map(([key,label])=><label key={key} className="text-sm">{label}<input className={field} value={bank[key]||''} onChange={e=>setBank({...bank,[key]:e.target.value})}/></label>)}</div><label className="block text-sm">คำแนะนำการชำระ<textarea className={field} value={bank.instructions||''} onChange={e=>setBank({...bank,instructions:e.target.value})}/></label><div className="flex gap-3 items-end"><label className="flex-1 text-sm">รูป QR รับชำระของโรงแรม<input className={field} value={bank.qrUrl||''} onChange={e=>setBank({...bank,qrUrl:e.target.value})}/></label><ImageUploadButton onUploadSuccess={url=>setBank({...bank,qrUrl:url})}/></div><p className="text-xs text-neutral-500">ใช้รูป QR จากบัญชีโรงแรมจริง ลูกค้าต้องระบุยอดโอนและแนบสลิป เจ้าหน้าที่เป็นผู้ตรวจสอบการชำระ</p></div>
      <button disabled={busy} className={button+' !bg-orange-700 !text-white'}><Save size={17}/>{busy?'กำลังดำเนินการ…':'บันทึกการตั้งค่าทั้งหมด'}</button>
    </form>
    <div className="bg-white border rounded-xl p-5 space-y-4"><h3 className="font-bold">รายการแจ้งโอน ({payments.filter(p=>p.status==='pending').length} รอตรวจสอบ)</h3>{!payments.length&&<p className="text-sm text-neutral-500">ยังไม่มีรายการแจ้งโอน</p>}{payments.map(p=><div key={p.id} className="border rounded-lg p-4 flex flex-wrap gap-4 justify-between items-center text-sm"><div><b>{p.bookingId} · {p.guestName}</b><p>{p.amount.toLocaleString()} บาท · {p.transferredAt.replace('T',' ')} · ผู้โอน {p.payerName}</p><p className="text-xs text-neutral-500">{p.status==='pending'?'รอตรวจสอบ':p.status==='approved'?'รับชำระแล้ว':'ปฏิเสธ'} {p.note}</p></div><div className="flex gap-3 items-center"><a href={'/api/payments/'+p.id+'/slip'} target="_blank" rel="noreferrer" className="underline text-orange-700">เปิดสลิป</a>{p.status==='pending'&&<><button disabled={busy} type="button" className={button} onClick={()=>{if(window.confirm('ตรวจสอบยอดเข้าบัญชีโรงแรมแล้ว และยืนยันรับชำระรายการนี้?'))void action(async()=>{await api('/api/payments/'+p.id+'/review','POST',{status:'approved'});await load();await refreshSettings();setMessage('บันทึกผลตรวจสอบแล้ว');});}}><CheckCircle size={16}/>รับชำระ</button><button disabled={busy} onClick={()=>{const note=window.prompt('เหตุผลที่ไม่รับสลิปนี้');if(note)void action(async()=>{await api('/api/payments/'+p.id+'/review','POST',{status:'rejected',note});await load();});}}>ปฏิเสธ</button></>}</div></div>)}</div>
    <div className="bg-white border rounded-xl p-5 space-y-3"><h3 className="font-bold">ประวัติการแจ้งเตือน</h3><p className="text-xs text-neutral-500">เมื่อส่งไม่สำเร็จ ระบบลองใหม่อัตโนมัติสูงสุด 3 ครั้ง</p>{!jobs.length&&<p className="text-sm text-neutral-500">ยังไม่มีประวัติการส่ง</p>}{jobs.map(j=><div key={j.id} className="border-b py-3 text-sm flex flex-wrap justify-between gap-3"><div><b>{j.channel.toUpperCase()} · {j.subject}</b><p className="text-neutral-500 text-xs">{j.recipient} · {new Date(j.createdAt).toLocaleString('th-TH')} · ครั้งที่ {j.attempts}</p>{j.error&&<p className="text-red-600 text-xs">{j.error}</p>}</div><div><span>{labels[j.status]||j.status}</span>{['failed','pending'].includes(j.status)&&<button className="ml-3 text-orange-700 underline" onClick={()=>void action(async()=>{await api('/api/notifications/'+j.id+'/retry','POST',{});await load();})}>ลองส่งใหม่</button>}</div></div>)}</div>
  </section>;
}
