import React,{useState,useEffect} from 'react';
export default function PaymentForm({booking}:{booking:any}){
  const [settings,setSettings]=useState<any>({}),[amount,setAmount]=useState(booking.totalPrice),[payerName,setPayerName]=useState(booking.guestName),[transferredAt,setTransferredAt]=useState(''),[slip,setSlip]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{fetch('/api/payment-settings').then(r=>r.json()).then(d=>setSettings(d.settings));},[]);
  const field='block w-full rounded-lg border border-neutral-700 bg-neutral-950 p-3 mt-1';
  return <section className="border-t border-neutral-700 pt-5 space-y-4"><h3 className="font-semibold text-lg">แจ้งโอนเงิน</h3>{settings.bankName&&<div className="text-sm text-neutral-300 p-4 bg-neutral-950 rounded-lg"><p>{settings.bankName} · {settings.accountNumber}</p><p>ชื่อบัญชี: {settings.accountName}</p><p>{settings.instructions}</p></div>}{settings.qrUrl&&<img src={settings.qrUrl} alt="QR รับชำระของโรงแรม" className="max-w-48 mx-auto bg-white p-2 rounded"/>}
    {message?<p role="status" className="text-green-400">{message}</p>:<form className="space-y-3 text-sm" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingId:booking.id,email:booking.guestEmail,amount,payerName,transferredAt,slip})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
      <label className="block">ยอดเงินที่โอน<input required className={field} type="number" min="0.01" step="0.01" max={booking.totalPrice} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label className="block">ชื่อผู้โอน<input required className={field} value={payerName} onChange={e=>setPayerName(e.target.value)}/></label><label className="block">วันและเวลาโอน (เวลาไทย)<input required className={field} type="datetime-local" value={transferredAt} onChange={e=>setTransferredAt(e.target.value)}/></label><label className="block">แนบสลิป (JPG, PNG, WebP ไม่เกิน 5 MB)<input required className={field} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setSlip('');const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('ไฟล์ต้องไม่เกิน 5 MB');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{setSlip(String(reader.result));setError('');};reader.readAsDataURL(file);}}/></label>{slip&&<img alt="สลิปที่เลือก" src={slip} className="max-h-48 mx-auto"/>}{error&&<p role="alert" className="text-red-400">{error}</p>}<button disabled={busy||!slip} className="w-full py-3 rounded-lg bg-orange-700 disabled:opacity-50">{busy?'กำลังส่ง…':'ส่งข้อมูลแจ้งโอน'}</button><p className="text-xs text-neutral-400">การแนบสลิปยังไม่ถือว่าชำระสำเร็จ จนกว่าเจ้าหน้าที่ตรวจสอบยอดเข้าบัญชี</p>
    </form>}
  </section>;
}
